#!/usr/bin/env bash
# ==============================================================================
# apply_hardening.sh — vulnScan Companion Remediation Script
#
# Version  : 0.3.0
# License  : MIT
# Platform : Fedora / RHEL / CentOS (bash 5+)
# Project  : https://github.com/cainepavl/vulnScan
# ==============================================================================
#
# Run as: sudo bash apply_hardening.sh
# Safe to re-run (idempotent). Creates backups before any edit.

set -u

RED='\033[1;31m'; GREEN='\033[1;32m'; YELLOW='\033[1;33m'
CYAN='\033[1;36m'; RESET='\033[0m'; DIM='\033[2m'

ok()   { echo -e "  ${GREEN}[OK]${RESET}  $1"; }
info() { echo -e "  ${CYAN}[--]${RESET}  $1"; }
warn() { echo -e "  ${YELLOW}[!!]${RESET}  $1"; }
fail() { echo -e "  ${RED}[ERR]${RESET} $1"; }
section() {
    local sep; sep=$(printf '─%.0s' {1..60})
    echo ""; echo -e "${CYAN}${sep}${RESET}"
    echo -e "${CYAN}  $1${RESET}"
    echo -e "${CYAN}${sep}${RESET}"; echo ""
}

if [[ "$EUID" -ne 0 ]]; then
    echo -e "${RED}ERROR: must run as root — use: sudo bash apply_hardening.sh${RESET}"
    exit 1
fi

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║   vulnScan — Applying Hardening Fixes                   ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${RESET}"
echo ""

# ── 1. KERNEL SYSCTL HARDENING ─────────────────────────────────────────────
section "1/4  Kernel sysctl Hardening"

SYSCTL_FILE="/etc/sysctl.d/99-hardening.conf"

if [[ -f "$SYSCTL_FILE" ]]; then
    cp "$SYSCTL_FILE" "${SYSCTL_FILE}.bak.$(date +%Y%m%d%H%M%S)"
    info "Existing $SYSCTL_FILE backed up"
fi

cat > "$SYSCTL_FILE" << 'EOF'
# vulnScan hardening — kernel parameters
# Generated by apply_hardening.sh

# Full ASLR — randomises code/stack/heap locations to hinder memory-corruption exploits
kernel.randomize_va_space = 2

# Hide kernel pointers from all users — prevents KASLR bypass via /proc
kernel.kptr_restrict = 2

# Restrict kernel ring buffer to root — prevents info-leakage of kernel addresses
kernel.dmesg_restrict = 1

# Prevent SUID binaries from creating core dumps (stops privileged memory exposure)
fs.suid_dumpable = 0

# Restrict ptrace to parent→child relationships only (blocks process injection)
kernel.yama.ptrace_scope = 1

# SYN cookie flood protection — defends against SYN-flood DoS without allocating state early
net.ipv4.tcp_syncookies = 1

# Disable IP source routing — source-routed packets can bypass routing policy and firewalls
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Reject ICMP redirect packets — prevents silent routing table manipulation (MitM vector)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Disable sending ICMP redirects — this host should not alter peer routing tables
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Strict reverse path filtering — rejects packets that wouldn't route back the same way
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Log packets with impossible source addresses — indicates IP spoofing or misconfiguration
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Ignore broadcast ICMP echo requests — prevents Smurf DoS amplification
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Drop malformed ICMP error responses — reduces noise and attack surface
net.ipv4.icmp_ignore_bogus_error_responses = 1
EOF

ok "Written $SYSCTL_FILE"
chmod 644 "$SYSCTL_FILE"

# Apply immediately without requiring a reboot
if sysctl --system &>/dev/null; then
    ok "sysctl --system applied (settings are live)"
else
    fail "sysctl --system failed — settings may not be active (check: journalctl -xe)"
fi

# Spot-verify the three highest-impact values
for key in kernel.kptr_restrict kernel.yama.ptrace_scope fs.suid_dumpable; do
    val=$(sysctl -n "$key" 2>/dev/null)
    info "  $key = $val"
done

# ── 2. SSH HARDENING ────────────────────────────────────────────────────────
section "2/4  SSH Daemon Hardening"

SSHD_CFG="/etc/ssh/sshd_config"

if [[ ! -f "$SSHD_CFG" ]]; then
    warn "sshd_config not found — SSH server not installed, skipping"
else
    # Back up the original config — abort this section if backup fails
    SSHD_BAK="${SSHD_CFG}.bak.$(date +%Y%m%d%H%M%S)"
    if ! cp "$SSHD_CFG" "$SSHD_BAK"; then
        fail "Could not back up sshd_config (disk full?) — skipping SSH section"
    else
        ok "Backed up sshd_config → $SSHD_BAK"

        # Helper: set a directive in sshd_config.
        # Deletes all existing occurrences (active or commented) then appends the clean value.
        # Uses | as sed delimiter so directive values containing / are safe.
        set_sshd() {
            local directive="$1"
            local value="$2"
            sed -i -E "\|^[[:space:]#]*${directive}[[:space:]]|Id" "$SSHD_CFG"
            echo "${directive} ${value}" >> "$SSHD_CFG"
            info "  ${directive} = ${value}"
        }

        # PermitRootLogin — direct root login bypasses sudo audit trail and exposes
        # a known target username to brute-force attacks
        set_sshd "PermitRootLogin" "no"

        # MaxAuthTries — limits attempts per connection before disconnect
        # Default is 6; 3 slows brute-force without impacting legitimate users
        set_sshd "MaxAuthTries" "3"

        # X11Forwarding — tunnels the X display over SSH; not needed on servers
        set_sshd "X11Forwarding" "no"

        # NOTE: PasswordAuthentication intentionally left unchanged.
        # Disabling it before SSH keys are configured would lock out remote access.
        warn "PasswordAuthentication left as-is — disable only after SSH keys are deployed"

        # Validate config before restarting — if sshd -t fails, restore backup
        if sshd -t 2>/dev/null; then
            ok "sshd config validated (sshd -t passed)"
            systemctl restart sshd
            ok "sshd restarted"
        else
            fail "sshd config test FAILED — restoring backup"
            cp "$SSHD_BAK" "$SSHD_CFG"
            fail "Backup restored — SSH changes were NOT applied"
        fi
    fi
fi

# ── 3. PASSWORD & LOCKOUT POLICY ────────────────────────────────────────────
section "3/4  Password & Account Lockout Policy"

PWQUALITY_CONF="/etc/security/pwquality.conf"
FAILLOCK_CONF="/etc/security/faillock.conf"

# pam_pwquality — enforce a minimum password length of 14 characters
# NIST SP 800-63B recommends at least 8 but 12–14 is the current best practice
if [[ -f "$PWQUALITY_CONF" ]]; then
    cp "$PWQUALITY_CONF" "${PWQUALITY_CONF}.bak.$(date +%Y%m%d%H%M%S)"
    info "Backed up pwquality.conf"
    if grep -q "^minlen" "$PWQUALITY_CONF"; then
        # Update existing setting
        sed -i 's/^minlen\s*=.*/minlen = 14/' "$PWQUALITY_CONF"
    else
        echo "minlen = 14" >> "$PWQUALITY_CONF"
    fi
    ok "pwquality.conf — minlen set to 14"
else
    warn "$PWQUALITY_CONF not found — skipping minlen"
fi

# pam_faillock — lock accounts after 5 failed login attempts
# This defends against online brute-force without frustrating legitimate users
if [[ -f "$FAILLOCK_CONF" ]]; then
    cp "$FAILLOCK_CONF" "${FAILLOCK_CONF}.bak.$(date +%Y%m%d%H%M%S)"
    info "Backed up faillock.conf"
    if grep -q "^deny" "$FAILLOCK_CONF"; then
        sed -i 's/^deny\s*=.*/deny = 5/' "$FAILLOCK_CONF"
    else
        echo "deny = 5" >> "$FAILLOCK_CONF"
    fi
    ok "faillock.conf — deny set to 5"
else
    warn "$FAILLOCK_CONF not found — skipping faillock"
fi

# ── 4. UNNECESSARY SERVICES ─────────────────────────────────────────────────
section "4/4  Disabling Unnecessary Services"

disable_svc() {
    local svc="$1"
    local reason="$2"
    if systemctl is-active --quiet "$svc" 2>/dev/null \
       || systemctl is-enabled --quiet "$svc" 2>/dev/null; then
        if systemctl disable --now "$svc" 2>/dev/null; then
            ok "Disabled: ${svc} — ${reason}"
        else
            fail "Could not disable ${svc} — check: systemctl status ${svc}"
        fi
    else
        info "Already inactive: ${svc}"
    fi
}

# CUPS print spooler — not needed unless this machine is used for printing
# Re-enable with: sudo systemctl enable --now cups
disable_svc "cups"        "print spooler (re-enable if you print from this machine)"
disable_svc "cups-browsed" "network printer discovery"

# Avahi mDNS — .local hostname resolution and Bonjour device discovery
# Re-enable with: sudo systemctl enable --now avahi-daemon
disable_svc "avahi-daemon" "mDNS/Zeroconf (re-enable if .local names or Bonjour devices are needed)"

# Bluetooth — disable if no Bluetooth peripherals are in use
# Re-enable with: sudo systemctl enable --now bluetooth
disable_svc "bluetooth"   "Bluetooth stack (re-enable if BT peripherals are in use)"

# ── SUMMARY ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║   Hardening complete — ready to re-run vulnScan         ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  ${DIM}Re-run the audit:  sudo bash vulnScan.sh${RESET}"
echo ""
